# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Unit tests for baffle query, analyze, and render modules."""

import datetime
import unittest

from analyze import classify_ai_attestation
from analyze import classify_user
from common import ATTESTATION_CROSS
from common import ATTESTATION_TICK
from common import ATTESTATION_WARNING
from common import CLASSIFICATION_BOT
from common import CLASSIFICATION_HUMAN
from common import ISSUE_CATEGORY_BUGS
from common import ISSUE_CATEGORY_ENHANCEMENTS
from common import ISSUE_CATEGORY_GOOD_FIRST
from common import ISSUE_CATEGORY_ORDER
from common import ISSUE_CATEGORY_SEARCH_LABELS
from common import ISSUE_GROUP_ICON
from query import build_issue_search
from query import build_search
from render import is_bug
from render import is_enhancement
from render import is_good_first_issue
from render import render_html


class TestBaffleCommon(unittest.TestCase):

    def test_issue_category_constants(self):
        self.assertEqual(ISSUE_CATEGORY_GOOD_FIRST, 'Good First Issues')
        self.assertEqual(ISSUE_CATEGORY_BUGS, 'Bugs')
        self.assertEqual(ISSUE_CATEGORY_ENHANCEMENTS, 'Enhancements')
        self.assertEqual(
            ISSUE_CATEGORY_ORDER,
            ['Good First Issues', 'Bugs', 'Enhancements'],
        )
        self.assertIn(ISSUE_CATEGORY_GOOD_FIRST, ISSUE_GROUP_ICON)
        self.assertIn(ISSUE_CATEGORY_BUGS, ISSUE_GROUP_ICON)
        self.assertIn(ISSUE_CATEGORY_ENHANCEMENTS, ISSUE_GROUP_ICON)

        labels_dict = dict(ISSUE_CATEGORY_SEARCH_LABELS)
        self.assertIn('good first issue', labels_dict[ISSUE_CATEGORY_GOOD_FIRST])
        self.assertIn('bug', labels_dict[ISSUE_CATEGORY_BUGS])
        self.assertIn('enhancement', labels_dict[ISSUE_CATEGORY_ENHANCEMENTS])


class TestBaffleQuery(unittest.TestCase):

    def test_build_search_pr(self):
        search = build_search()
        self.assertIn('is:pr', search)
        self.assertIn('state:open', search)
        self.assertIn('org:ros2', search)
        self.assertIn('org:ament', search)
        self.assertIn('-repo:ros2/rosbag2', search)

    def test_build_issue_search(self):
        search_gfi = build_issue_search('label:"good first issue"')
        self.assertIn('is:issue', search_gfi)
        self.assertIn('state:open', search_gfi)
        self.assertIn('archived:false', search_gfi)
        self.assertIn('org:ros2', search_gfi)
        self.assertIn('org:ament', search_gfi)
        self.assertIn('-repo:ros2/rosbag2', search_gfi)
        self.assertIn('label:"good first issue"', search_gfi)
        self.assertNotIn('is:pr', search_gfi)

    def test_build_issue_search_with_weeks(self):
        search = build_issue_search('label:bug,bugs', weeks=2)
        self.assertIn('updated:>=', search)
        self.assertIn('label:bug,bugs', search)


class TestBaffleAnalyze(unittest.TestCase):

    def test_classify_ai_attestation_pr(self):
        body_no = "## Description\nFixes issue\n\n### Did you use Generative AI?\n\nNo\n\n### Additional Information\nNone"
        self.assertEqual(classify_ai_attestation(body_no), ATTESTATION_CROSS)

        body_yes = "## Description\nFixes issue\n\n### Did you use Generative AI?\n\nYes, GPT-4 for tests\n\n### Additional Information\nNone"
        self.assertEqual(classify_ai_attestation(body_yes), ATTESTATION_TICK)

        body_empty = "Just a quick bug fix"
        self.assertEqual(classify_ai_attestation(body_empty), ATTESTATION_WARNING)

    def test_classify_ai_attestation_issue(self):
        body_issue_no_resp = "### Operating System:\nLinux\n\n### Generated by Generative AI\n\n_No response_\n\n### Steps to reproduce\nRun node"
        self.assertEqual(classify_ai_attestation(body_issue_no_resp), ATTESTATION_WARNING)

        body_issue_no = "### Operating System:\nLinux\n\n### Generated by Generative AI\n\nNo\n\n### Steps to reproduce\nRun node"
        self.assertEqual(classify_ai_attestation(body_issue_no), ATTESTATION_CROSS)


class TestBaffleRender(unittest.TestCase):

    def test_issue_filter_predicates(self):
        self.assertTrue(is_good_first_issue({'labels': ['good first issue', 'help wanted']}))
        self.assertTrue(is_good_first_issue({'labels': ['Good First Issue']}))
        self.assertFalse(is_good_first_issue({'labels': ['bug']}))

        self.assertTrue(is_bug({'labels': ['bug']}))
        self.assertTrue(is_bug({'labels': ['bugs']}))
        self.assertTrue(is_bug({'labels': ['BUG']}))
        self.assertFalse(is_bug({'labels': ['enhancement']}))

        self.assertTrue(is_enhancement({'labels': ['enhancement']}))
        self.assertTrue(is_enhancement({'labels': ['enhancements']}))
        self.assertFalse(is_enhancement({'labels': ['bug']}))

    def test_render_html_tabs_and_tables(self):
        sample_data = {
            'pull_requests': [
                {
                    'repo': 'ros2/rclcpp',
                    'title': 'Sample PR 1',
                    'url': 'https://github.com/ros2/rclcpp/pull/101',
                    'kind': 'PR',
                    'author': 'alice',
                    'created': '2026-09-20T10:00:00+00:00',
                    'updated': '2026-09-24T12:00:00+00:00',
                    'body': 'PR description',
                    'ai_attestation': 'cross',
                }
            ],
            'issues': [
                {
                    'repo': 'ros2/rclcpp',
                    'title': 'Easy cleanup task',
                    'url': 'https://github.com/ros2/rclcpp/issues/201',
                    'kind': 'Issue',
                    'author': 'bob',
                    'created': '2026-09-18T10:00:00+00:00',
                    'updated': '2026-09-24T14:00:00+00:00',
                    'body': 'Good first issue description',
                    'labels': ['good first issue'],
                    'ai_attestation': 'cross',
                },
                {
                    'repo': 'ros2/rclpy',
                    'title': 'Null pointer crash in executor',
                    'url': 'https://github.com/ros2/rclpy/issues/301',
                    'kind': 'Issue',
                    'author': 'carol',
                    'created': '2026-09-15T10:00:00+00:00',
                    'updated': '2026-09-23T11:00:00+00:00',
                    'body': 'Bug report details',
                    'labels': ['bug'],
                    'ai_attestation': 'warning',
                },
                {
                    'repo': 'ament/ament_cmake',
                    'title': 'Support custom build flags',
                    'url': 'https://github.com/ament/ament_cmake/issues/401',
                    'kind': 'Issue',
                    'author': 'dave',
                    'created': '2026-09-10T10:00:00+00:00',
                    'updated': '2026-09-22T09:00:00+00:00',
                    'body': 'Feature request',
                    'labels': ['enhancement'],
                    'ai_attestation': 'tick',
                },
            ],
            'users': {
                'alice': {'classification': 'Human', 'account_age_days': 500, 'public_pull_requests': 20, 'is_ros_maintainer': True},
                'bob': {'classification': 'Human', 'account_age_days': 100, 'is_ros_maintainer': False},
                'carol': {'classification': 'Unknown', 'account_age_days': 50, 'is_ros_maintainer': False},
                'dave': {'classification': 'Human', 'account_age_days': 800, 'is_ros_maintainer': True},
            }
        }

        html_out = render_html(sample_data, datetime.datetime(2026, 9, 25, 12, 0, tzinfo=datetime.timezone.utc))

        # Check tabs exist and are placed above the hero badge
        self.assertIn('data-tab="pull-requests"', html_out)
        self.assertIn('data-tab="issues"', html_out)
        self.assertIn('id="tab-pull-requests"', html_out)
        self.assertIn('id="tab-issues"', html_out)
        self.assertLess(html_out.index('class="tab-nav"'), html_out.index('id="hero-badge"'))

        # Check PR tab content
        self.assertIn('Sample PR 1', html_out)
        self.assertIn('ros2/rclcpp#101', html_out)

        # Check Issue tab content and 3 tables
        self.assertIn('Good First Issues', html_out)
        self.assertIn('Bugs', html_out)
        self.assertIn('Enhancements', html_out)

        self.assertIn('Easy cleanup task', html_out)
        self.assertIn('Null pointer crash in executor', html_out)
        self.assertIn('Support custom build flags', html_out)

        self.assertIn('ros2/rclcpp#201', html_out)
        self.assertIn('ros2/rclpy#301', html_out)
        self.assertIn('ament/ament_cmake#401', html_out)

        # Check maintainer badge on alice and dave
        self.assertIn('title="ROS maintainer">&#9733;</span>', html_out)

        # Check JavaScript tab switching and hash listener
        self.assertIn('function switchTab(tabId)', html_out)
        self.assertIn('window.location.hash', html_out)


if __name__ == '__main__':
    unittest.main()
